plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  - History.md
  - WhatIs\*.md
  - WhereIs\*.md
  - HowToPart\*.md
  - WhoIsIn\*.md
  - Shared\*.md
theme: jekyll-theme-leap-day