title: I Love Azure
author: Roberto Albano
email: ila.org@hotmail.com
description: I Love Azure community manifest
markdown: kramdown
baseurl: ""
destination: _docs
twitter_username: _iloveazure
plugins:
  - jekyll-relative-links
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-figure
theme: jekyll-theme-leap-day
layout: default