plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  - History.md
  - WhatIs\*.md
  - WhereIs\*.md
  - HowToPart\*.md
  - WhoIsIn\*.md
  - _Shared\*.md
  - _Shared\_Processes\_Contributor\*.md
  - _Shared\_Processes\_Editor\*.md
  - _Shared\_Processes\_Social\*.md
  - _Templates\*.md
theme: jekyll-theme-leap-day