title: I Love Azure
author: Roberto Albano
email: ila.community@hotmail.com
description: I Love Azure community manifest
markdown: kramdown
baseurl: ""
destination: _docs
url: "iloveazure.org"
twitter_username: _iloveazure
plugins:
  - jekyll-relative-links
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-figure
theme: jekyll-theme-leap-day
include:
  - /*.md
port: 8671
layout: default